[package]
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
build = "build.rs"
edition = "2018"
name = "gl-typed"
version = "0.1.0"

[features]
default = []

[dependencies]
generic-array = "0.12.0"

[build-dependencies]
gl_generator = "0.10.0"

[dev-dependencies]
