//! This module proviles the OpenGL constants as you know them.

use crate::symbols::*;

pub const ACTIVE_ATOMIC_COUNTER_BUFFERS: ActiveAtomicCounterBuffers = ActiveAtomicCounterBuffers;
pub const ACTIVE_ATTRIBUTES: ActiveAttributes = ActiveAttributes;
pub const ACTIVE_ATTRIBUTE_MAX_LENGTH: ActiveAttributeMaxLength = ActiveAttributeMaxLength;
pub const ACTIVE_UNIFORMS: ActiveUniforms = ActiveUniforms;
pub const ACTIVE_UNIFORM_BLOCKS: ActiveUniformBlocks = ActiveUniformBlocks;
pub const ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH: ActiveUniformBlockMaxNameLength = ActiveUniformBlockMaxNameLength;
pub const ACTIVE_UNIFORM_MAX_LENGTH: ActiveUniformMaxLength = ActiveUniformMaxLength;
pub const ATTACHED_SHADERS: AttachedShaders = AttachedShaders;
pub const COMPILE_STATUS: CompileStatus = CompileStatus;
pub const COMPUTE_SHADER: Compute = Compute;
pub const COMPUTE_WORK_GROUP_SIZE: ComputeWorkGroupSize = ComputeWorkGroupSize;
pub const DELETE_STATUS: DeleteStatus = DeleteStatus;
pub const FALSE: False = False;
pub const FRAGMENT_SHADER: Fragment = Fragment;
pub const GEOMETRY_INPUT_TYPE: GeometryInputType = GeometryInputType;
pub const GEOMETRY_OUTPUT_TYPE: GeometryOutputType = GeometryOutputType;
pub const GEOMETRY_SHADER: Geometry = Geometry;
pub const GEOMETRY_SHADER_INVOCATIONS: GeometryShaderInvocations = GeometryShaderInvocations;
pub const GEOMETRY_VERTICES_OUT: GeometryVerticesOut = GeometryVerticesOut;
pub const INFO_LOG_LENGTH: InfoLogLength = InfoLogLength;
pub const LINK_STATUS: LinkStatus = LinkStatus;
pub const PROGRAM_BINARY_RETRIEVABLE_HINT: ProgramBinaryRetrievableHint = ProgramBinaryRetrievableHint;
pub const PROGRAM_SEPARABLE: ProgramSeparable = ProgramSeparable;
pub const RENDERER: Renderer = Renderer;
pub const SHADER_SOURCE_LENGTH: ShaderSourceLength = ShaderSourceLength;
pub const SHADER_TYPE: ShaderType = ShaderType;
pub const SHADING_LANGUAGE_VERSION: ShadingLanguageVersion = ShadingLanguageVersion;
pub const TESS_CONTROL_OUTPUT_VERTICES: TessControlOutputVertices = TessControlOutputVertices;
pub const TESS_CONTROL_SHADER: TessControl = TessControl;
pub const TESS_EVALUATION_SHADER: TessEvaluation = TessEvaluation;
pub const TESS_GEN_MODE: TessGenMode = TessGenMode;
pub const TESS_GEN_POINT_MODE: TessGenPointMode = TessGenPointMode;
pub const TESS_GEN_VERTEX_ORDER: TessGenVertexOrder = TessGenVertexOrder;
pub const TRANSFORM_FEEDBACK_BUFFER_MODE: TransformFeedbackBufferMode = TransformFeedbackBufferMode;
pub const TRANSFORM_FEEDBACK_VARYINGS: TransformFeedbackVaryings = TransformFeedbackVaryings;
pub const TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH: TransformFeedbackVaryingMaxLength = TransformFeedbackVaryingMaxLength;
pub const TRUE: True = True;
pub const VALIDATE_STATUS: ValidateStatus = ValidateStatus;
pub const VENDOR: Vendor = Vendor;
pub const VERSION: Version = Version;
pub const VERTEX_SHADER: Vertex = Vertex;
